spring:
  datasource:
    url: jdbc:mysql://database-1.clq4nrif3ipe.ap-northeast-2.rds.amazonaws.com:3306/hansang
    username: admin
    password: hansang2023

  jpa:
      hibernate:
        ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 23a33748bc0ac018a7af658bfd48c34b
            client-secret: 347y1aSMUikM8LCEJdiCmaV2HLPt0oFn
            redirect-uri: http://localhost:8080/oauth/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secretKey: dsdfnndfgjnfnjerhrgndfjvdfj3y4t6454856y83r93fjurhfge723t43r7878796969ll

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
